document.addEventListener("DOMContentLoaded",function(){
    let cache=[],type="all",query="";
    async function waitForAdmin(){for(let i=0;i<30;i++){if(window.dosteaAdminUser)return true;await new Promise(r=>setTimeout(r,100));}return false;}
    async function load(){if(!(await waitForAdmin()))return;const {data,error}=await window.supabaseClient.from("admin_activity_logs").select("id,admin_user_id,action,entity_type,entity_id,summary,metadata,created_at").order("created_at",{ascending:false}).limit(250);if(error){window.dosteaToast?.("Activity Error",error.message);return;}cache=data||[];render();}
    function render(){const rows=cache.filter(row=>(type==="all"||row.entity_type===type)&&(!query||`${row.summary} ${row.action} ${row.entity_type}`.toLowerCase().includes(query)));document.getElementById("activityTable").innerHTML=rows.length?`<table class="admin-table"><thead><tr><th>TIME</th><th>ACTION</th><th>ENTITY</th><th>SUMMARY</th><th>ADMIN ID</th></tr></thead><tbody>${rows.map(row=>`<tr><td><span class="cell-title">${new Date(row.created_at).toLocaleDateString("en-IN")}</span><span class="cell-sub">${new Date(row.created_at).toLocaleTimeString("en-IN")}</span></td><td>${window.dosteaStatusPill(row.action)}</td><td><span class="cell-title">${window.dosteaSafe(row.entity_type)}</span><span class="cell-sub">${window.dosteaSafe(row.entity_id||"")}</span></td><td>${window.dosteaSafe(row.summary)}</td><td><span class="cell-sub">${window.dosteaSafe(row.admin_user_id)}</span></td></tr>`).join("")}</tbody></table>`:'<div class="empty-state">No admin activity found.</div>';}
    document.querySelectorAll("#activityTabs [data-type]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("#activityTabs .admin-tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");type=btn.dataset.type;render();}));
    document.getElementById("activitySearch").addEventListener("input",e=>{query=e.target.value.trim().toLowerCase();render();});
    window.addEventListener("dostea-admin-refresh",load);waitForAdmin().then(ok=>{if(!ok)return;load();window.supabaseClient.channel("dostea-admin-activity-page").on("postgres_changes",{event:"INSERT",schema:"public",table:"admin_activity_logs"},load).subscribe();});
});
