document.addEventListener("DOMContentLoaded",function(){
    let cache=[];const modal=document.getElementById("couponModal");
    async function waitForAdmin(){for(let i=0;i<30;i++){if(window.dosteaAdminUser)return true;await new Promise(r=>setTimeout(r,100));}return false;}
    async function load(){if(!(await waitForAdmin()))return;const {data,error}=await window.supabaseClient.from("coupons").select("*").order("created_at",{ascending:false});if(error){window.dosteaToast?.("Coupon Error",error.message);return;}cache=data||[];render();}
    function render(){document.getElementById("couponsTable").innerHTML=cache.length?`<table class="admin-table"><thead><tr><th>CODE</th><th>DISCOUNT</th><th>MINIMUM</th><th>USAGE</th><th>ENDS</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>${cache.map(c=>`<tr><td><span class="cell-title">${window.dosteaSafe(c.code)}</span><span class="cell-sub">${window.dosteaSafe(c.description||"")}</span></td><td>${c.discount_type==="percent"?Number(c.discount_value)+"%":window.dosteaMoney(c.discount_value)}</td><td>${window.dosteaMoney(c.min_order_amount)}</td><td>${Number(c.used_count||0)} / ${c.usage_limit??"∞"}</td><td>${c.ends_at?new Date(c.ends_at).toLocaleString("en-IN"):"No expiry"}</td><td>${c.is_active?'<span class="status-pill status-ready">Active</span>':'<span class="status-pill status-cancelled">Inactive</span>'}</td><td><button class="table-action" data-edit="${c.id}" type="button">Edit</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty-state">No coupons created.</div>';document.querySelectorAll("[data-edit]").forEach(btn=>btn.addEventListener("click",()=>openEdit(btn.dataset.edit)));}
    function close(){modal.classList.remove("show");document.body.classList.remove("modal-open");}
    function openNew(){document.getElementById("couponForm").reset();document.getElementById("couponId").value="";document.getElementById("couponModalTitle").textContent="New Coupon";modal.classList.add("show");document.body.classList.add("modal-open");}
    function openEdit(id){const c=cache.find(row=>row.id===id);if(!c)return;document.getElementById("couponId").value=c.id;document.getElementById("promoCode").value=c.code;document.getElementById("discountType").value=c.discount_type;document.getElementById("discountValue").value=c.discount_value;document.getElementById("minOrder").value=c.min_order_amount;document.getElementById("maxDiscount").value=c.max_discount??"";document.getElementById("usageLimit").value=c.usage_limit??"";document.getElementById("endsAt").value=c.ends_at?new Date(c.ends_at).toISOString().slice(0,16):"";document.getElementById("couponActive").value=String(c.is_active);document.getElementById("couponDescription").value=c.description||"";document.getElementById("couponModalTitle").textContent="Edit Coupon";modal.classList.add("show");document.body.classList.add("modal-open");}
    document.getElementById("couponForm").addEventListener("submit",async e=>{e.preventDefault();const id=document.getElementById("couponId").value;const payload={code:document.getElementById("promoCode").value.trim().toUpperCase(),discount_type:document.getElementById("discountType").value,discount_value:Number(document.getElementById("discountValue").value),min_order_amount:Number(document.getElementById("minOrder").value||0),max_discount:document.getElementById("maxDiscount").value?Number(document.getElementById("maxDiscount").value):null,usage_limit:document.getElementById("usageLimit").value?Number(document.getElementById("usageLimit").value):null,ends_at:document.getElementById("endsAt").value?new Date(document.getElementById("endsAt").value).toISOString():null,is_active:document.getElementById("couponActive").value==="true",description:document.getElementById("couponDescription").value.trim()||null,updated_at:new Date().toISOString()};const result=id?await window.supabaseClient.from("coupons").update(payload).eq("id",id):await window.supabaseClient.from("coupons").insert(payload);if(result.error){window.dosteaToast?.("Coupon Save Failed",result.error.message);return;}close();window.dosteaToast?.("Coupon Saved",`${payload.code} is ready.`);load();});
    document.getElementById("newCoupon").addEventListener("click",openNew);document.getElementById("closeCouponModal").addEventListener("click",close);modal.addEventListener("click",e=>{if(e.target===modal)close();});window.addEventListener("dostea-admin-refresh",load);waitForAdmin().then(ok=>{if(ok)load();});
});
